GR_RANGES = {
    "Halite": {"min": 0, "max": 30},
    "Sylvite": {"min": 500, "max": 747},
    "Bischofite": {"min": 0, "max": 0},
    "Carnallite": {"min": 100, "max": 220},
    "Tachydrite": {"min": 0, "max": 10},
    "Kainite": {"min": 245, "max": 285.42},
    "Anhydrite": {"min": 0, "max": 70},
    "Gypsum": {"min": 0, "max": 0},
    "Kieserite": {"min": 0, "max": 0},
    "Langbeinite": {"min": 268, "max": 290},
    "Polyhalite": {"min": 180, "max": 200},
    "Barite": {"min": 0, "max": 0},
    "Calcite": {"min": 10, "max": 100},
    "Dolomite": {"min": 10, "max": 20},
    "Silt / Sandstone": {"min": 0, "max": 60},
    "Clay / Mudstone": {"min": 10, "max": 1000},
}

DT_RANGES = {
    "Halite": {"min": 65, "max": 73},
    "Sylvite": {"min": 74, "max": 74},
    "Bischofite": {"min": 100, "max": 100},
    "Carnallite": {"min": 58, "max": 78},
    "Tachydrite": {"min": 92, "max": 92},
    "Kainite": {"min": None, "max": None},
    "Anhydrite": {"min": 49, "max": 67},
    "Gypsum": {"min": 52.5, "max": 52.5},
    "Kieserite": {"min": None, "max": None},
    "Langbeinite": {"min": 52, "max": 52},
    "Polyhalite": {"min": 57.5, "max": 57.5},
    "Barite": {"min": None, "max": None},
    "Calcite": {"min": 44, "max": 90},
    "Dolomite": {"min": 58, "max": 58},
    "Silt / Sandstone": {"min": 55, "max": 88},
    "Clay / Mudstone": {"min": 48, "max": 170},
}

RHOB_RANGES = {
    "Halite": {"min": 1.9, "max": 2.3},
    "Sylvite": {"min": None, "max": None},
    "Bischofite": {"min": None, "max": None},
    "Carnallite": {"min": 1.57, "max": 2.2},
    "Tachydrite": {"min": 1.66, "max": 1.72},
    "Kainite": {"min": None, "max": None},
    "Anhydrite": {"min": 2.03, "max": 2.98},
    "Gypsum": {"min": None, "max": None},
    "Kieserite": {"min": None, "max": None},
    "Langbeinite": {"min": None, "max": None},
    "Polyhalite": {"min": None, "max": None},
    "Barite": {"min": None, "max": None},
    "Calcite": {"min": 2.3, "max": 2.9},
    "Dolomite": {"min": 2.683, "max": 2.88},
    "Silt / Sandstone": {"min": 2.04, "max": 2.9},
    "Clay / Mudstone": {"min": 1.6, "max": 2.95},
}

NPHI_RANGES = {
    "Halite": {"min": -3, "max": 0},
    "Sylvite": {"min": -3, "max": 0},
    "Bischofite": {"min": 60, "max": 100},
    "Carnallite": {"min": 60, "max": 65},
    "Tachydrite": {"min": 50, "max": 100},
    "Kainite": {"min": 45, "max": 60},
    "Anhydrite": {"min": -2, "max": 0},
    "Gypsum": {"min": 49, "max": 60},
    "Kieserite": {"min": None, "max": None},
    "Langbeinite": {"min": None, "max": None},
    "Polyhalite": {"min": None, "max": None},
    "Barite": {"min": None, "max": None},
    "Calcite": {"min": None, "max": None},
    "Dolomite": {"min": 1, "max": 4},
    "Silt / Sandstone": {"min": None, "max": None},
    "Clay / Mudstone": {"min": 25, "max": 60},
}

PEF_RANGES = {
    "Halite": {"min": 4.65, "max": 4.72},
    "Sylvite": {"min": 8.51, "max": 8.76},
    "Bischofite": {"min": None, "max": None},
    "Carnallite": {"min": 4.09, "max": 4.29},
    "Tachydrite": {"min": 3.82, "max": 3.84},
    "Kainite": {"min": None, "max": None},
    "Anhydrite": {"min": 5.05, "max": 5.1},
    "Gypsum": {"min": 3.99, "max": 4},
    "Kieserite": {"min": 1.8, "max": 1.83},
    "Langbeinite": {"min": None, "max": None},
    "Polyhalite": {"min": None, "max": None},
    "Barite": {"min": None, "max": None},
    "Calcite": {"min": None, "max": None},
    "Dolomite": {"min": 3.09, "max": 3.14},
    "Silt / Sandstone": {"min": 1.7, "max": 2.7},
    "Clay / Mudstone": {"min": 3, "max": 5},
}
